# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('team', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='pitcher',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawling.Player'),
        ),
        migrations.AddField(
            model_name='hitter',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawling.Player'),
        ),
    ]
