# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20170606_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='away_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
