# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source ‘https://github.com/ProjectInTheClass/KBO.git’

target 'kbo_3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kbo_3

  target 'kbo_3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kbo_3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
