# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=110)),
                ('team', models.CharField(blank=True, max_length=110)),
                ('rate', models.FloatField(default=0)),
                ('homerun', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=110)),
                ('team', models.CharField(blank=True, max_length=110)),
                ('era', models.FloatField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('so', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=110)),
                ('home_pitcher', models.CharField(max_length=110)),
                ('away_team', models.CharField(max_length=110)),
                ('away_pitcher', models.CharField(max_length=110)),
                ('stadium', models.CharField(max_length=110)),
                ('time', models.CharField(max_length=110)),
                ('day', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
            ],
        ),
    ]
