# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitter',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
