# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_hitter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('diff', models.FloatField(default=0)),
                ('late', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='hitter',
            old_name='hit',
            new_name='homerun',
        ),
        migrations.RenameField(
            model_name='hitter',
            old_name='number',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='pitcher',
            old_name='save',
            new_name='so',
        ),
        migrations.RemoveField(
            model_name='hitter',
            name='info',
        ),
        migrations.RemoveField(
            model_name='pitcher',
            name='info',
        ),
        migrations.AddField(
            model_name='hitter',
            name='name',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='hitter',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hitter',
            name='team',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='era',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='name',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='team',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
