# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_auto_20170519_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='late',
            new_name='rate',
        ),
    ]
