# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='away_pitcher',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='home_pitcher',
        ),
    ]
