# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_schedule_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.Gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.User')),
            ],
        ),
    ]
