# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0008_entrylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrylist',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediction',
            name='check',
            field=models.CharField(default='fail', max_length=110),
        ),
        migrations.AddField(
            model_name='prediction',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
